version: '3'

services:
  broker-service:
    build:
      context: ../broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    environment:
      PORT: "8080"
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ../authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    environment:
      PORT: "8081"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=CET"
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:15.1'
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/